### ISSUE TITLE
CI/CD with Netlify

### ISSUE THREAD

**Issue by swimjiy** [mkdev-genie/mkdev-front#36]
둘이 같이 github actions에 netlify를 연결합니다.

관련한 링크를 아래에 첨부합니다.
https://dev.to/curtiscodes/ci-cd-pipeline-with-netlify-and-github-actions-bcm

**Comment by swimjiy** [comment]
**[버그 노트]**
이슈:  Deploy는 완료되었다고 나오는데 배포된 페이지에 Access Denied가 뜨는 문제
![스크린샷 2021-02-03 오전 12 44 44](https://user-images.githubusercontent.com/38487811/106624449-04ded680-65b9-11eb-89fd-a1f2580605bb.png)

해결:
1. `Deploy to Netlify` step을 거치기 전에 `npm ci`, `npm run build` 커맨드를 추가하여 배포에 필요한 파일들을 `build/` 디렉토리에 추가.
2. `publish-dir` 를 `./build` 로 수정하고 더불어 production-branch도 `main` 으로 변경
3. 이래도 안되길래 netlify에서 빌드되는 도메인 이름을 mkdev로 수정했더니 해결.

이것저것 다 때려넣어서 해결이 된 거라 정확히 무엇이 문제였을지 애매하네요😂  그냥 다 조금씩 문제가 있었던 걸로...

**Comment by jiyoon1156** [comment]
크흡 저는 그래도 access denied 뜨는데 권한 문제일까요😂  지영님은 그 링크로 들어갔을 때 잘 나오시나요??

**Comment by swimjiy** [comment]
> 크흡 저는 그래도 access denied 뜨는데 권한 문제일까요😂 지영님은 그 링크로 들어갔을 때 잘 나오시나요??

도메인을 변경한거라 https://mkdev.netlify.app/ 요 링크로 들어와보시겠어요??

**Comment by jiyoon1156** [comment]
> > 크흡 저는 그래도 access denied 뜨는데 권한 문제일까요😂 지영님은 그 링크로 들어갔을 때 잘 나오시나요??
> 
> 도메인을 변경한거라 https://mkdev.netlify.app/ 요 링크로 들어와보시겠어요??

아차차 위에 도메인을 변경하셨다고 이야기하셨었군요! 잘 나오네요! 감삼다ㅎㅎ
