### ISSUE TITLE
dotenv없이 CI/CD 할 수 있는 방법 찾아보기

### ISSUE THREAD

**Issue by swimjiy** [mkdev-genie/mkdev-front#44]
보안 상의 이슈로 원격 레포에는 dotenv파일을 올릴 수 없으므로, Actions에서 프로젝트를 빌드할 때 dotenv 파일 없이 필요한 키 값을 읽어올 수 있는 방법을 찾아봅니다.

**Comment by jiyoon1156** [comment]
https://stackoverflow.com/questions/52540316/how-do-i-add-a-env-file-in-gitlab-ci-during-deployment-stage 이렇게 해보는거 어떨까요? github secrets에 우리 env 설정 만들어놓은다음에 -> 배쉬파일만들고(secrets로 .env 파일 생성 및 입력) -> 그 배쉬파일 실행하는걸 yml 에 추가하는데 권한 우리만 보게 설정

**Comment by swimjiy** [comment]
> https://stackoverflow.com/questions/52540316/how-do-i-add-a-env-file-in-gitlab-ci-during-deployment-stage 이렇게 해보는거 어떨까요? github secrets에 우리 env 설정 만들어놓은다음에 -> 배쉬파일만들고(secrets로 .env 파일 생성 및 입력) -> 그 배쉬파일 실행하는걸 yml 에 추가하는데 권한 우리만 보게 설정

오 괜찮을 것 같네요 한 번 도전해보고 오겠습니다.
